yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: "node-modules"
npmScopes:
  "agriaku":
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
    # npmRegistryServer: "http://localhost:4873"
    npmAuthToken: ${GITHUB_TOKEN}
# unsafeHttpWhitelist:
#   - localhost
